version: '3.9'

services:

  api:
    build: .
    container_name: fastapi_api
    ports:
      - "8000:8000"
    volumes:
      - .:/app

    command: >
      sh -c "uv run alembic upgrade head &&
             uv run uvicorn app.app:app --host 0.0.0.0 --port 8000 --reload"
    env_file:
      - .env
    depends_on:
      - db

  db:
    image: postgres:16
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_DB: fast_db
      POSTGRES_USER: fast_user
      POSTGRES_PASSWORD: 1234
    ports:
      - "5434:5432"
