"""mobile number optional

Revision ID: 1d40187e866a
Revises: 52d4a23cf286
Create Date: 2026-05-11 13:37:41.350811

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1d40187e866a'
down_revision: Union[str, Sequence[str], None] = '52d4a23cf286'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('user', 'mobile',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
